version: "3.9"
secrets:
  config_file:
    file: todoistbot/config.properties-example

services:
  todoist:
    container_name: todoist_container
    image: fffatigue/todoistbot
    secrets:
      - config_file
    environment:
      TODOIST_CONFIG_PATH: /run/secrets/config_file